# Generated by Django 5.2.8 on 2025-11-22 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ormapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Max_Retail_Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Name',
            new_name='product_Name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Reference_Id',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Feedback',
        ),
    ]
